#!/bin/bash
# newk
# v. 0.40
# This is Free Software under GNU GPL v3.0 or a BSD-3-Clause, as you prefer ;-)
# Copyright 2023 Reynaldo Cordero Corro, Mercedes Cordero Martínez
#
# https://gitlab.com/HaskellKatas/katas--proof-of-concept
#
# * To start a new Haskell kata, BDD/TDD style, in few seconds.
#   It uses *stack* and *hpack*. Ready to use QuickCheck and Hspec.
#
# * To create a kata (www.codewars.com style, at the time), start by giving as parameters:
#   * the name of the kata,
#   * the link of the exercise prepared for the kata and
#   * (an optional) comment.
#
#  As a result, you will obtain a 100% FLOSS full hackable kata environment:
#    * One bash script at the wheel, offering instrucctions, tools  and contextual help
#    * A directory bookmarking application for fast access                    [cdargs]
#    * A special and integrated workflow for a control version application       [git]
#    * Ready to edit source and testing code with control [emacs haskell-mode + Dante]
#
# * Your katas will be placed next to the other libraries in a directory you can set.
#
## Main usage:
#    newk KATANAME REF [COMMENT]     # to create a new kata
#    newk KATANAME                   # to reopen an existing kata
#
## Features:
#    newk [-h | --help]
#
###

VERSION='v0.40' # Codemotion Madrid

U="\033[4m"  # underline ON
B="\033[1m"  # bold ON
B_="\033[0m" # bold OFF  (every other mark is OFF too)

LBLUE_B="\e[104m" # Light blue (background)
LCYAN="\e[96m"    # Light cyan
LGRAY="\e[37m"    # Light gray
LGREEN="\e[92m"   # Light green

AZ_L="abcdefghijklmnopqrstuvwxyz"
AZ_U="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
NU="0123456789"
CODEWARS="www.codewars.com"

## Kata directory root:
#GITLAB_GITHUB="GITHUB"
GITLAB_GITHUB="GITLAB"
#LIBROOT_CW="${HOME}/git/${GITLAB_GITHUB}/CW"
LIBROOT_CW="${HOME}/haskellkatas"

## Some other variables:
# https://www.stackage.org/
# Next line might be updated if you use the recomended installer

RESOLVER="lts-22.44"  # ghc-9.6.7, Published on 2025-05-02

TERMINAL_NAMES=("stack ghci" "git diff" "stack build" "Command - git")
EDITOR_NAME="KATA: "

#GIT_DEFAULT_BRANCH="main"
#GIT_DEFAULT_BRANCH=$(git config --get init.defaultBranch)
GITLOGT='git log --graph --pretty=format:'\
'"%C(red)%h%C(reset)%C(green) (%cd)%C(reset)%n %s%C(yellow)%d%C(reset)"'\
' --date=format:"%Y-%m-%d %H:%M:%S" --branches'

GITLOGT2='git log --graph --pretty=format:'\
'"%s%C(yellow)%d%C(reset) %C(red)%h%C(reset)"'

GITLOGT_MOST_RECENT='git log ${BRNCH} -n1 --pretty=format:'\
'"%C(red)%h%C(reset) %s%C(yellow)%d%C(reset)"'\
' --date=format:"%Y-%m-%d %H:%M:%S"'

GITLOGT_MOST_RECENT_='git log ${BRNCH} -n1 --pretty=format:%h'

GITLOGT_MOST_RECENT_MESSAGE='echo -n -e "${B}${LCYAN}"; git branch -v --format="%(subject)" | uniq ; echo -n -e "${B_}"'
GITLOGT_MOST_RECENT_MESSAGE_='git branch -v --format="%(subject)" | uniq'

#NEXT_BRANCH_XX_ALREADY_CREATED='git log -1 --decorate --oneline ${GIT_DEFAULT_BRANCH}_base |
#                                cut -d " " -f2- | grep -Eo "[0-9][0-9]"'
# | sed -n "s/^\([0-9][0-9]\)$/\1/p"
# | sed -n 's/^[ \*]*//;s/^\([0-9][0-9]\)$/\1/p' | sort | tail -1
# Retrieve all exist branch names like '00', '01', .. '99', sort them ant take the last
NEXT_BRANCH_XX_ALREADY_CREATED="git branch |
 sed -n 's/^[ \*]*//;s/^\([0-9][0-9]\)$/\1/p' | sort | tail -1"
## geometry: lines x columns + px horizontal + px vertical
## Screen Resolution (1080p): 1920x1080  
GEOM_EMACS="72x27+589+0"   # editor (Emacs)
GEOM_TERM1="65x29+0+0"     # Term1
GEOM_TERM2="65x27+0+610"   # Term2
GEOM_TERM3="75x26+589+650" # Term3
GEOM_TERM0="65x55+0+15"    # Term0 (hidden)

P_CAT_HASKELL="pygmentize -f terminal256 -O style=native -l haskell"

PROGRAM_NAME="$(basename "$0")"

README="cat README.md"

SRC_FILE=$(echo src/*)  # It must match only one file

TEMPDIR=".stack-work/newk/"

EXAMPLES="Examples:
${PROGRAM_NAME} multiply https://www.codewars.com/kata/50654ddff44f800200000004/train/haskell 'Multiply'
${PROGRAM_NAME} greet    https://www.codewars.com/kata/523b4ff7adca849afe000035/train/haskell 'Function 1 - hello world'
${PROGRAM_NAME} multiply       # To continue working on the existing kata multiply
${PROGRAM_NAME} multiply.data  # To continue working on the kata multiply using data already preloaded"

## COMMITS="git rev-list --count $(git branch --show-current)"
## COMMITS_MAIN="git rev-list --count main"
## COMMITS_MASTER="git rev-list --count master"

function main_or_master_branch()
{

  if [[ -n "$(git branch | grep  -e " master$")" ]] ; then
    GIT_DEFAULT_BRANCH="master"
  elif [[ -n "$(git branch | grep  -e " main$")" ]]; then
    GIT_DEFAULT_BRANCH="main"
  else
    echo -e "${B}*** There is no 'main' or 'master' branch ***${B_}"
  fi
}


function commits_current_branch() {
  git rev-list --count "$(git branch --show-current)"
}


function exist_branch_XX(){
  p="${1}"
  if [[ -z "${p}" ]]; then
    echo "Parameter missing."
    exit 1
  fi
  git branch | grep -w "${p}" # if-then-else: Non empty string means true. Empty string means false.
}


function commits_branch_XX() {
  p="${1}"
  if [[ -z "${p}" ]]; then
    echo "Parameter missing"
    exit 1
  fi
  if [[ $(exist_branch_XX "${p}") ]]; then
    :
  else
    echo "Branch does not exist"
    exit 1
  fi
  git rev-list --count "${p}"
}


USAGE="${B}${PROGRAM_NAME}${B_}: Haskell Kata training. (${U}${VERSION}${B_})

${PROGRAM_NAME} KATANAME [REF] [COMMENT]

${PROGRAM_NAME} [-h|--help] | [-p|--present] | [-q|--quit]
${PROGRAM_NAME} [-1|--first-red]
${PROGRAM_NAME} [-2|--extended-tests]
${PROGRAM_NAME} [-3|--next]
${PROGRAM_NAME} [-b|--branch] BRANCH
${PROGRAM_NAME} [-0|--log] | [-00|--log2] | [-000|--log3] ...
${PROGRAM_NAME} [-ss|--show-slow | [-sf|--show-fast]
${PROGRAM_NAME} [-s|--show BRANCH [BRANCH] [BRANCH] ...
${PROGRAM_NAME} [-c|--compare] C1 C2 [C3]

where:
  -h|--help            show this help text
  -p|--present         present kata's windows (editor & terminals)
  -q|--quit            quit windows (aka. close all & exit)

  -0|--log|[-00|-log2] show logs, status and instructions

  -1|--first-red       do once when your kata is completely set up
  -2|--extended-tests  commit your own kataficated solution (on branch 00)
  -3|--next            commit a kataficated solution. Start a new branch
  -b|--branch BRANCH   update/kataficate an existent solution in its BRANCH

  -s|--show BRANCH     show solution on a particular BRANCH (or BRANCHES)
 -ss|--show-slow       show all solutions   (With syntax parsing)
 -sf|--show-fast       show all solutions   (No syntax parsing)
  
  -c|--compare C1 C2 [C3]   compare between solutions C1 C2 [C3]

  KATANAME             must begin with a letter
                       and contain only alphanumeric char
  REF                  reference. i.e.:
                       webpage of the kata training problem
  COMMENT              Some info about the kata (give a title is nice)
                       (enclose the COMMENT phrase into single quotes)
  BRANCH               Git branch
    00:          Your solution will be placed here
    01, 02, etc: Other solutions will be placed there

Typical usage:
  ${PROGRAM_NAME} KATANAME REF [COMMENT]
     -> set up a brand new kata and open an editor
          and 3 bash terminals with tools.
     -> if kataName already exists, you will be asked
        if you want to work on it

${EXAMPLES}
"

# Options and parameters
while [[ $# -gt 0 ]]
do
key="${1}"

case ${key} in
    -h|--help)
    HELP=YES
    shift
    ;;
    -q|--quit)
    QUIT=YES
    shift
    ;;
    -1|--first-red)
    K1=YES
    shift
    ;;
    -2|--extended-tests)
    K2=YES
    shift
    ;;
    -3|--next)
    K3=YES
    shift
    ;;
    -b|--branch)
    BRANCHWORK=YES
    shift
    ;;
    -0|--log)
    LOG=YES
    shift
    ;;
    -00|--log2)
    LOG2=YES
    shift
    ;;
    -000|--log3)
    LOG3=YES
    shift
    ;;
    -0000|--log4)
    LOG4=YES
    shift
    ;;
    -00000|--log5)
    LOG5=YES
    shift
    ;;
    -i|--instructions)
    INSTRUCTIONS=YES
    shift
    ;;
    -s|--show)
    SHOWSELECTED=YES
    shift
    ;;
    -ss|--show-slow)
    SHOW=YES
    shift
    ;;
    -sf|--show-fast)
    SHOW=YES
    FAST=YES
    shift
    ;;
    -c|--compare)
    COMPARE=YES
    shift
    ;;
    -p|--present)
    PRESENT=YES
    shift
    ;;
    *)
    POSITIONAL+=("${1}") # save it in an array for later
    shift # past argument
    ;;
esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ ${POSITIONAL:0:1} == "-" ]]; then
  echo -e "\n${B}Unknown option${B_}: -> ""${POSITIONAL[0]}""\n"
  HELP=YES
fi
####


function check()
{
if [[ "${HELP}" == "YES" ]]; then
  echo
  echo -e "${USAGE}"
  exit 0
fi

if [[ "${SHOWSELECTED}" == "YES" ]]; then
  showSelectedBranches "$@"
  exit 0
fi

if [[ "${SHOW}" == "YES" ]]; then
  show
  exit 0
fi

if [[ "${COMPARE}" == "YES" ]]; then
  compare "${1}" "${2}" "${3}" &
  exit 0
fi

if [[ "${QUIT}" == "YES" ]]; then
  quit_windows
  exit 0
fi

if [[ "${PRESENT}" == "YES" ]]; then
  present_windows
  exit 0
fi

if [[ "${LOG}" == "YES" || "${LOG2}" == "YES" || "${LOG3}" == "YES" || "${LOG4}" == "YES" ]]; then
  main_or_master_branch
  k0 
  exit 0
fi

if [[ "${LOG5}" == "YES" ]]; then
  main_or_master_branch
  k0 "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}"
  exit 0
fi

if [[ "${INSTRUCTIONS}" == "YES" ]]; then
  instructions
  exit 0
fi

if [[ "${K1}" == "YES" ]]; then
  main_or_master_branch
  k1 ""
  exit 0
fi

if [[ "${K2}" == "YES" ]]; then
  main_or_master_branch
  k2 ""
  exit 0
fi

if [[ "${K3}" == "YES" ]]; then
  main_or_master_branch
  k3 ""
  exit 0
fi

if [[ "${BRANCHWORK}" == "YES" ]]; then
  if [[ -n "$(git diff --name-only)" ]] ; then
    echo -e -n "Your local changes will be overwritten by checkout. OK? [Y/n] " ; read -r -e answ
    if [[ "${answ}" == "" ]] || [[ "${answ}" == "y" ]] || [[ "${answ}" == "Y" ]]; then
      git stash   # so you can 'git stash pop' later on a fresh new branch
    else
      LOG5=YES
      INSTRUCTIONS=YES
      k0
      exit 0
    fi
  fi
  git checkout "${1}"
  LOG5=YES
  INSTRUCTIONS=YES
  k0
  exit 0
fi

NAME=$(eval "echo '${1}' | sed 's/[/]//g'")  # strip slashes. Useful when you are in LIBROOT directory, and use autocompletation(TAB) to get kata's name
REF="${2}"
COMMENT="${3}"

if [[ "${NAME}" =~ ".data"$ ]]; then
  DATA=".data"
  NAME=${NAME%.data}
else
  DATA=""
fi

if [[ "${NAME}" =~ [^${AZ_L}${AZ_U}${NU}]+ ]] ; then
  echo -e "
Error: ${B}${NAME}${B_} must only contain alphanumeric characters. It must begin with a letter.
"
  exit 1
fi

case "${NAME:0:1}" in
  [${AZ_L}] | [${AZ_U}])
    # echo "${NAME} begin with a letter. It's Okay."
    :
    ;;
  "")
    echo -e "
Error: ${B}No kataName provided!${B_}

${EXAMPLES}

For more information: ${B}${PROGRAM_NAME} --help${B_}
"
    exit 1
    ;;
  *)
    echo -e "
Error: ${B}${NAME}${B_} is not allowed. It must begin with a letter. Try again.
"
    exit 1
    ;;
esac

LIB_U=$(eval "echo ${NAME} | sed 's/^./\u&/'")  # NameOfTheNewLib. First letter to uppercase
LIB_L=$(eval "echo ${NAME} | sed 's/^./\l&/'")  # NameOfTheNewLib. First letter to lowercase

if [ -z "${LIB_L}"  ]; then
  echo -e "
${USAGE}"
  exit 1
fi

CW_T=""

if [ -d "${LIBROOT_CW}/${LIB_L}${DATA}" ]; then
  CW_T="CW"
  echo "
Kata found in ${LIBROOT_CW}/${LIB_L}${DATA}

- - - - - - - - -
"
fi

if [[ ${CW_T} == "CW" ]] ; then
  echo -e -n "'${B}${LIB_L}${B_}' name has already used. (CodeWars)
Reopen kata '${B}${LIB_L}${B_}' (CodeWars) ? [Y/n] " ; read -r -e answ
  if [[ "${answ}" == "" ]] || [[ "${answ}" == "y" ]] || [[ "${answ}" == "Y" ]]; then
    EDIT_EXISTING_KATA="YES"
    LIBROOT=${LIBROOT_CW}
    CW_T="EDIT"
  fi
fi

if [[ ${CW_T} == "CW" ]]; then
  echo "Then bye!"
  exit 1
fi

REF_T=$(echo "${REF}" | tr '[:upper:]' '[:lower:]')

if [[ ${CW_T} == "EDIT" ]] ; then
  echo -e "
Reopen kata '${B}${LIB_L}${B_}'"
elif [ -z "${REF}" ] && [ -z "${CW_T}" ] ; then
  echo -e "
When creating a new kata... Error: ${B}REF${B_} missing.

  REF example: https://www.codewars.com/kata/CHANGETHIS/train/haskell

${PROGRAM_NAME} KATANAME ${B}REF${B_} ${B}[COMMENT]${B_}
"
  exit 1
elif [ -z "${CW_T}" ] &&  [[ ${REF_T} =~ ${CODEWARS} ]] ; then
  echo -e "
Create kata '${B}${LIB_L}${B_}' (CodeWars)."
  LIBROOT="${LIBROOT_CW}"
else
  echo -e "
Remember that REF must be from ${B}${CODEWARS}${B_}."
  exit 1
fi

if [ ! -d "${LIBROOT}" ]; then
  echo -n -e "You're going to create this root directory to store your katas:

  ${B}${LIBROOT}${B_}

Do you want to proceed? [Y/n] " ; read -r -e answ
  if [[ "${answ}" == "" ]] || [[ "${answ}" == "y" ]] || [[ "${answ}" == "Y" ]]; then
    mkdir -p "${LIBROOT}"
  else
    echo " Bye!"
    exit 1
  fi
fi
}


function quit_windows()
{
pkill -f "${EDITOR_NAME}"
for i in "${!TERMINAL_NAMES[@]}"; do
  pkill -f "${TERMINAL_NAMES[$i]}"
done
}


function present_windows()
{
EDITOR_WINDOW=$( xdotool search --name "${EDITOR_NAME}" )
TERMINAL_WINDOWS0=$( xdotool search --name "${TERMINAL_NAMES[0]}" )
TERMINAL_WINDOWS1=$( xdotool search --name "${TERMINAL_NAMES[1]}" )
TERMINAL_WINDOWS2=$( xdotool search --name "${TERMINAL_NAMES[2]}" )
TERMINAL_WINDOWS3=$( xdotool search --name "${TERMINAL_NAMES[3]}" )

xdotool windowactivate --sync "${EDITOR_WINDOW}"
xdotool windowactivate --sync "${TERMINAL_WINDOWS0}"
xdotool windowactivate --sync "${TERMINAL_WINDOWS1}"
xdotool windowactivate --sync "${TERMINAL_WINDOWS2}"
xdotool windowactivate --sync "${TERMINAL_WINDOWS3}"
}


function checkUpdatedTests()
{
test=$(git diff test)
if [[ "${test}" == "" ]]; then
  :
else
  echo "New tests!"
  oriBranch=$(git branch --show-current)
  git stash --quiet -- test
  other=$(git diff)

  if [[ "${other}" == "" ]]; then
    if [[ $(exist_branch_XX ${GIT_DEFAULT_BRANCH}_base) ]] ; then

      git checkout --quiet ${GIT_DEFAULT_BRANCH}_base
      git checkout --quiet stash@\{0\} -- test
      echo "Tests updated:"
      pkill pager
      git commit -am "First red (tests updated) (${oriBranch})"
      git checkout --quiet "${oriBranch}"
      git stash pop --quiet
    else
      :
      # git checkout --quiet ${GIT_DEFAULT_BRANCH}_base

      git checkout --quiet stash@\{0\} -- test
      echo "Tests updated:"
      pkill pager
      git commit -am "Tests updated (${oriBranch})"
      git checkout --quiet "${oriBranch}"
      git stash pop --quiet
    fi
  else
    if [[ $(exist_branch_XX ${GIT_DEFAULT_BRANCH}_base) ]] ; then

      git stash --quiet -- .
      git checkout --quiet ${GIT_DEFAULT_BRANCH}_base
      git checkout --quiet stash@\{1\} -- test
      echo "Tests updated:"
      pkill pager
      git commit -am "First red (tests updated) (${oriBranch})"
      git checkout --quiet "${oriBranch}"
      git stash pop --quiet
      git stash pop --quiet
    else
      :

      git stash --quiet -- .
      # git checkout --quiet ${GIT_DEFAULT_BRANCH}_base
      git checkout --quiet stash@\{1\} -- test
      echo "Tests updated:"
      pkill pager
      git commit -am "Tests updated (${oriBranch})"
      git checkout --quiet "${oriBranch}"
      git stash pop --quiet
      git stash pop --quiet
    fi
  fi
fi
}


function k1()
{
error="$(stack build --test --fast 2> /dev/null)"
error_last_line=$(echo "${error}" | tail -n1)

expand_current_branch() {
  git branch --show-current
}

expand_on_git_default_branch() {
  expand_current_branch | grep "^${GIT_DEFAULT_BRANCH}$"
}
expand_commits_git_default_branch() {
  git rev-list --count ${GIT_DEFAULT_BRANCH}
}

phase_one_not_apply() {
  echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -1${B_}  script doesn't apply.
In phase one, you are setting up the code for the first time
  and looking for a ${B}RED${B_}) state for the first time:

Your code should compile successfully,
  should have appropriate tests
  and should NOT pass these tests in a simple way.
"
}


if [[ "$(expand_on_git_default_branch)"  == "${GIT_DEFAULT_BRANCH}" ]] && [[ $(commits_branch_XX "${GIT_DEFAULT_BRANCH}") == "1" ]]; then
  :
else
  echo -n -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -1${B_}  script doesn't apply.

You have already passed phase one.

please ${B}hit the enter key${B_} to see the instructions: " ; read -r
  LOG5=YES
  INSTRUCTIONS=YES
  k0
  exit 1
fi

if [[ "${error_last_line}" == *"0 failure"* ]] ; then
  # compile OK, Pass tests OK
  phase_one_not_apply
  echo -e "Please, make your code NOT to pass the tests
  (Tip: use function 'undefined')
"
  exit
elif [[ "${error_last_line}" == "" ]]; then
  # compile NOK
  phase_one_not_apply
  echo -e "Your code doesn't compile.
  Please, fix your code so it can run at least
  (Tip: probably there's a grammar issue)
"
else
  # compile OK, Pass tests NOK

  if [ "$(expand_on_git_default_branch)" == "${GIT_DEFAULT_BRANCH}" ]; then
    echo "git commit -am 'First red'"
    pkill pager
    git commit -am 'First red'
    INSTRUCTIONS=YES
    k0
  else
    phase_one_not_apply
    echo -e "You are not on branch ${B}${GIT_DEFAULT_BRANCH}${B_}.
  (You are on branch ${B}$(expand_current_branch){B_})
  from your current branch you can't pass phase one.

Please ${B}hit the enter key${B_} to see the instructions: " ; read -r
    INSTRUCTIONS=YES
    k0
    exit 1
  fi
fi
}


function k2()
{

stack build --test --fast >/dev/null 2>&1

if [ "$?" -ne 0 ] ; then
  echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -2${B_}  script doesn't apply.
Code ${B}must pass${B_} tests. (${B}GREEN${B_})
"
  exit 1
else
  if [[ $(exist_branch_XX 00) ]] ; then
    echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -2${B_}  script doesn't apply.

Branch '00' exists. It seems that you have already executed  ${B}${PROGRAM_NAME} -2${B_}.
"
    exit 1
  fi
  if [[ ! "$(git log --pretty=format:'%s' | grep "First red")" =~ ^"First red" ]]; then
    echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -2${B_}  script doesn't apply.

It seems that you haven't executed  ${B}${PROGRAM_NAME} -1${B_}  before
"
    exit 1
  fi
  git log --oneline --branches
  echo -e "
Please, enter a commit message: (${B}CTRL-C to cancel${B_})"
  read -r -e COMMIT_MESSAGE
  checkUpdatedTests
  pkill pager
  if git add test/ && git commit -m 'First red (tests updated)' ; then
    echo "
extended tests

This is your current log now:"
    eval "${GITLOGT}"
  else
    echo -e "
${B}NO${B_} extended tests"
  fi
  echo
  git stash 1> /dev/null && echo "Stashed the solution and create basic branches" \
    && git checkout -b ${GIT_DEFAULT_BRANCH}_base && git checkout -b 00 \
    && git stash pop  1> /dev/null
  echo "Popped back the solution
"
  pkill pager
  git commit -am "00 ${COMMIT_MESSAGE}"
  git checkout ${GIT_DEFAULT_BRANCH}_base && git checkout -b 01
  INSTRUCTIONS=YES
  k0
fi
}


function k3()
{
  nextXX()
  {
    current_branch=$(git branch --show-current)
    if [[ $(basename "$PWD") == *.data ]]; then
      NEXT_BRANCH_XX=$(( $(( 10#${current_branch} )) + 1))
      NEXT_BRANCH_XX=$( printf '%02d' ${NEXT_BRANCH_XX} )
    else
      nb_xx_ac="$(eval "$NEXT_BRANCH_XX_ALREADY_CREATED")"
      if [[ "${nb_xx_ac}" == "$(git branch --show-current)" ]]; then
        NEXT_BRANCH_XX=$(( $(( 10#${nb_xx_ac} )) + 1))
        NEXT_BRANCH_XX=$( printf '%02d' ${NEXT_BRANCH_XX} )
      else
        NEXT_BRANCH_XX="${nb_xx_ac}"
      fi
    fi

  }

if [[ ! $(exist_branch_XX 00) ]] ; then
  echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -3${B_}  script doesn't apply.
"
  if [ "$(commits_branch_XX "$(git branch --show-current)")" == "1" ] ; then
    echo -e "It seems that you haven't executed  ${B}${PROGRAM_NAME} -1${B_}  before"
  else
    echo -e "It seems that you haven't executed  ${B}${PROGRAM_NAME} -2${B_}."
  fi
  echo -n -e "
please ${B}hit the enter key${B_} to see the instructions: " ; read -r
  LOG5=YES
  INSTRUCTIONS=YES
  k0
  exit 1
fi

echo "Just be patient..."
error="$(stack build --test --fast 2> /dev/null)"
error_last_line=$(echo "${error}" | tail -n1)

if [[ "${error_last_line}" == *"0 failure"* ]] ; then
  # compile OK, Pass tests OK
  $PROGRAM_NAME -0000
  echo -e "${LGREEN}Current branch: $(git branch --show-current)${B_}"
  echo -e "Commit your kataficated code. After that you'll be moved to ${B}NEXT${B_} branch.
(${B}CTRL-C to cancel${B_})
Please, enter a commit message: "
  messageTMP="$(git log -1 --pretty=%B)"

  if [[ ${messageTMP} == "Tests updated (master)" ]] ; then
    read -r -e COMMIT_MESSAGE
  else
    set -f    # disable asterisk interpolation
    read -i "$(echo ${messageTMP} | cut -c 4-)" -e COMMIT_MESSAGE  # You need to remove the first 3 characters from the string
    set +f
  fi

  checkUpdatedTests
  pkill pager
  git commit -am "$(git branch --show-current) ${COMMIT_MESSAGE}"

  if [ "$?" -ne 0 ] ; then
    echo "ERROR when commit!"
    exit 1
  fi

  nextXX
  pkill pager

  git checkout ${GIT_DEFAULT_BRANCH}_base 2> /dev/null && (git checkout -b "${NEXT_BRANCH_XX}" 2> /dev/null || git checkout "${NEXT_BRANCH_XX}" 2> /dev/null)
  echo -e "(Switched to NEXT branch '${B}${NEXT_BRANCH_XX}${B_}')"
  INSTRUCTIONS=YES
  k0
elif [[ "${error_last_line}" == "" ]]; then
  # compile NOK
  echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -3${B_}  script doesn't apply.
Code doesn't compile.
Code ${B}must pass${B_} tests. (${B}GREEN${B_})
"
  exit 1
else
  # compile OK, Pass tests NOK
  echo -e "
${B}ERROR${B_}:  ${B}${PROGRAM_NAME} -3${B_}  script doesn't apply.
Code ${B}must pass${B_} tests. (${B}GREEN${B_})
"
  exit 1
fi

}


function showSelectedBranches()
{
a1=$(echo "***********************"
for var in "$@"
do
  messageT="$(git log -n1 --pretty=format:"%s" "${var}")"
  if [ -n "${messageT:0:3}" ] && [ "${messageT:0:3}" -eq "${messageT:0:3}" ] 2>/dev/null; then
    echo -e "($var) ${messageT:3}"
  else
    echo -e "($var) ${messageT}"
  fi
  echo -en "${LGREEN}"
  git show "${var}:./${SRC_FILE}"
  echo -e "${B_}***********************"
done)
echo "${a1}"
}


function show()
{

console=$(tty)
echo "Just be pacient..."  | tee "${console}" > /dev/null 2>&1

a1=$(echo -e "${B}${LBLUE_B}================== Heads of all solution branches${B_}"
  function gitlogt_most_recent_f()
  {
    var=0
    GITLOGT_MOST_RECENT_='git log $BRNCH -n1 --pretty=format:%h'

    while [ $? -eq 0 ]
    do
      BRNCH=$( printf '%02d' ${var} )
      var=$(( var + 1 ))
      eval "${GITLOGT_MOST_RECENT_}"w 2> /dev/null
    done
  }

index=0

readarray -dw -t linesArray <<<"$(gitlogt_most_recent_f)"

for commit in "${linesArray[@]}"
do
  size=${#commit}
  if [ "${size}" -lt 7 ]; then
    return
  else
    bb=$(git branch --contains "${commit}" | grep "${GIT_DEFAULT_BRANCH}_base")
    if [ -z "${bb}" ]; then
      padindex=$(printf %03d "${index}")
      echo -e "${LGRAY}-----------------------------------------------------${B_}
${LGRAY}-- ${padindex} ${SRC_FILE}${B_}
${B}${LCYAN}$(git log -n1 --pretty=format:"-- %s%d" "${commit}")${B_} ${commit}"
      if [[ ! $FAST == "YES" ]] ; then
        git show "${commit}:./${SRC_FILE}" | eval "${P_CAT_HASKELL}"
      else
        echo -e "${LGREEN}"
        git show "${commit}:./${SRC_FILE}"
        echo -e "${B_}"
      fi
      index=$(( index + 1 ))
    fi
  fi
done)

if [[ ! ${FAST} == "YES" ]] ; then
  echo "${a1}" | less -R
else
  echo "${a1}"
fi

}

function createfiles()
{
  mkdir -p $TEMPDIR

  file2=$(echo "$SRC_FILE" | sed 's/\//./g' )  # src.Multiply.hs

  function gitlogt_f()
  {
    var=0
    gitlogt_="git log --pretty=format:%h --branches --graph | sed '0,/ \* /{s/ \* /\n/}' | sed 's/[| /*]//g'"

    eval "${gitlogt_}" 2> /dev/null
  }

index=0
indexE=0

readarray -t linesArray <<<"$(gitlogt_f)"

for commit in "${linesArray[@]}"
do
  size=${#commit}
  if [ "$size" -lt 7 ]; then
    :
  else
    outf="$TEMPDIR${commit}.$file2"
    if [ -f "$outf" ]; then
      # echo "$outf"
      indexE=$(( indexE + 1 ))
    else
      # echo "=> $outf"
      git log -n1 --pretty=tformat:"-- %s%d" "$commit"  > "$outf"
      git show "$commit":./"$SRC_FILE"                 >> "$outf"
      index=$(( index + 1 ))
    fi
  fi
done
#echo "Created files:  $index"
#echo "Existent files: $indexE"
}

function compare() #C1 #C2 #[C3]
{
  error=""
  meld=""
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "$PROGRAM_NAME [-c|--compare] C1 C2 [C3]"
  else
    createfiles
    if [ ! -f "${TEMPDIR}$1"* ]; then  # Only one possible match. Gobbling is OK here
      echo "First parameter (Short Commit ID) is not OK:  ($1)"
      error="ERROR"
    fi
    if [ ! -f "${TEMPDIR}$2"* ]; then  # Only one possible match. Gobbling is OK here
      echo "Second parameter (Short Commit ID) is not OK: ($2)"
      error="ERROR"
    fi
    if [ -z "$3" ]; then
      meld="MELD2"
    else
      if [ -f "${TEMPDIR}$3"* ]; then  # Only one possible match. Gobbling is OK here
        meld="MELD3"
      else
        echo "Third (optional) parameter (Short Commit ID) is not OK: ($3)"
        error="ERROR"
      fi
    fi
    if [ "$error" == "ERROR" ]; then
      exit
    else
      #createfiles
      if [ "$meld" == "MELD2" ]; then
        meld ${TEMPDIR}"$1"* ${TEMPDIR}"$2"*
      elif [ "$meld" == "MELD3" ]; then
        meld ${TEMPDIR}"$1"* ${TEMPDIR}"$2"* ${TEMPDIR}"$3"*
      fi
    fi
  fi
}


function instructions()
{
if [ ! -d ".git" ]; then
  echo "
There's no git repository here.
No git log to show!
"
  exit 1
fi

echo "*******************"
git status
echo "*******************
"
# Force refresh git diff
touch .stack-work/tRiGgEr ; sleep 1 ; \
 rm .stack-work/tRiGgEr 2> /dev/null

nb_xx_ac="$(eval "$NEXT_BRANCH_XX_ALREADY_CREATED")"

if [[ $(exist_branch_XX "00") ]] ; then
  if [[ "$(git branch --show-current)" == "${nb_xx_ac}" ]]; then
    echo -e "${U}Next steps${B_}:
1) take a solution from ${KATA_GALORE} and update your local file:
  1.1) ${B}src/${LIB_U}.hs${B_}
2) ${B}kataficate${B_} code
3) use ${B}${PROGRAM_NAME} -3${B_}
   to commit changes and create a new branch to work on next solution
-- OR --------
1) use ${B}${PROGRAM_NAME} -b${B_} BRANCH
   to update/kataficate an existent solution in its BRANCH
"
  else
    echo -e "${U}Next steps${B_}:
1) ${B}Update / kataficate${B_} current solution:
  1.1) ${B}src/${LIB_U}.hs${B_}
2) use ${B}${PROGRAM_NAME} -3${B_}
   to commit changes in the current branch.
   Then you'll be automatically switched to NEXT branch.
-- OR --------
1) use ${B}${PROGRAM_NAME} -b${B_} BRANCH
   to update/kataficate an existent solution in its BRANCH
"
  fi
# boilerplate
#elif [[ $(commits_branch_XX $(git branch --show-current)) == "1" ]] ; then
elif [[ $(git branch --show-current) == "${GIT_DEFAULT_BRANCH}" ]] && [[ $(commits_branch_XX "${GIT_DEFAULT_BRANCH}") == "1" ]]; then
  sleep 0.4
  echo -e    "${U}Next steps${B_}:
1) Go to ${KATA_GALORE} and update these local files:
  1.1) ${B}src/${LIB_U}.hs${B_}       (types, parameters)
  1.1) ${B}test/${LIB_U}Spec.hs${B_}  ('describe', 'it' elements)
2) ${B}get a RED${B_} (code compile fine and do not pass tests)
3) then run  ${B}${PROGRAM_NAME} -1${B_}  to commit your 'first red'
   and follow the new instructions you'll see.
"

# first red. Create wip branch if needed  git log --pretty=format:'%s' -1
#elif [[ $(commits_branch_XX $(git branch --show-current)) == "2" ]] ; then
elif [[ "$(git log --pretty=format:'%s' -1)" =~ ^"First red" ]]; then
  echo -e "${U}Next steps${B_}:
1) ${B}Compose a solution${B_} (${B}GREEN${B_}).
2) ${B}Kataficate${B_} your code
3) Validate your code at the ${B}${KATA_GALORE}${B_} website
4) fetch ${B}extended tests${B_} from ${KATA_GALORE}.
  4.1) Clic on  ${B}View Solutions${B_}  button and then
  4.2) Clic on  ${B}Show Kata Test Cases${B_}  section
  4.3) ${B}Update${B_} your ${B}local${B_} copy of the tests.
5) then run  ${B}${PROGRAM_NAME} -2${B_}  to commit your solution.
"
else
  echo -e "Workflow of  ${B}${PROGRAM_NAME}${B_}  not standard. Be careful.
"
fi

}


function k0()
{
if [ ! -d ".git" ]; then
  echo "
There's no git repository here.
No git log to show!
"
  exit 1
fi

LIB_U=$(eval "basename ${PWD} .data | sed 's/^./\u&/'")  # NameOfTheLib. First letter to uppercase

if   [[ ${PWD} =~ ${LIBROOT_CW} ]]  ; then
  KATA_GALORE="CodeWars"
else
  KATA_GALORE="KATA_GALORE"
fi

if [[ "${LOG5}" == "YES" ]]; then
  eval "${GITLOGT2} $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}"
elif [[ "${LOG4}" == "YES" ]]; then
  eval "${GITLOGT_MOST_RECENT_MESSAGE}"
elif [[ "${LOG3}" == "YES" ]]; then
  eval "${GITLOGT_MOST_RECENT_MESSAGE_} | less -R"
elif [[ "${LOG2}" == "YES" ]]; then
  on=$(tput setaf 7; tput setab 4; tput bold) off=$(tput sgr0)
  git branch -v --format="%(objectname:short) %(subject)"\
   | uniq | sed "s/[^[:blank:]]\{1,\}/$on&$off/2"
else
  echo "
This is your current log:
"
  eval "${GITLOGT}" 2> /dev/null
fi

if [[ "${INSTRUCTIONS}" == "YES" ]]; then
  instructions
fi
}


function createNewKataCW()
{
# https://docs.codewars.com/languages/haskell/
echo -e "${B}${LIB_U}${B_} LIB is being prepared."

cd "${LIBROOT}" || (echo "** error(1): cd **" ; exit 1)

# Create, delete and update main files:
if [[ ${DATA} == ".data" ]]; then
  if [ -d "${LIBROOT}/${LIB_L}" ]; then
    mv "${LIBROOT}/${LIB_L}" "${LIBROOT}/${LIB_L}${DATA}_TMP" || (echo "** ERROR(6): cd **" ; exit 1)
  fi
fi

stack new "${LIB_L}" --resolver="${RESOLVER}"

cd "${LIBROOT}/${LIB_L}" || (echo "** ERROR(2): cd **" ; exit 1)

# Make sure these ghc-options must be off: Wall and Wmissing-export-lists
sed -i \
's/- -Wall/#- -Wall/g; '\
's/- -Wmissing-export-lists/#- -Wmissing-export-lists/g' "package.yaml"

echo "## ${REF}" >> README.md
echo "## ${COMMENT}" >> README.md

# https://stackoverflow.com/questions/5178828/how-to-replace-all-lines-between-two-points-and-subtitute-it-with-some-text-in-s

# - hspec-codewars # https://github.com/codewars/hspec-codewars
# - hspec-formatters-codewars # https://github.com/codewars/hspec-formatters-codewars

# Add dependencies for QuickCheck and hspec
sed -i '/^dependencies:/,/^- base >= 4.7 && < 5/'\
'c\dependencies:\n\- base >= 4.7 && < 5\n'\
'- array\n'\
'- bytestring\n'\
'- containers\n'\
'- heredoc\n'\
'- hscolour\n'\
'- polyparse\n'\
'- pretty-show\n'\
'- unordered-containers\n'\
'- Cabal\n'\
'- HUnit\n'\
'- QuickCheck\n'\
'- attoparsec\n'\
'- haskell-src-exts\n'\
'- hspec\n'\
'- hspec-attoparsec\n'\
'- hspec-contrib\n'\
'- hspec-megaparsec\n'\
'- HUnit-approx\n'\
'- lens\n'\
'- megaparsec\n'\
'- mtl\n'\
'- parsec\n'\
'- persistent\n'\
'- persistent-sqlite\n'\
'- persistent-template\n'\
'- random\n'\
'- regex-pcre\n'\
'- regex-posix\n'\
'- regex-tdfa\n'\
'- split\n'\
'- text\n'\
'- transformers\n'\
'- vector' "package.yaml"

# delete app scafolding and add hspec-discover. Add five default extensions
sed -i '/^  source-dirs: src/,/^tests:'/\
'c\  source-dirs: src\n\nbuild-tools:\n- hspec-discover\n\n'\
'default-extensions:\n- InstanceSigs\n- TypeApplications\n'\
'- ScopedTypeVariables\n- GADTSyntax\n- PartialTypeSignatures\n\n'\
'- OverloadedStrings\n\n'\
'tests:' "package.yaml"

##### stack test

rm -rf app
rm src/Lib.hs

# Spec.hs:
cat > test/Spec.hs << EOF
{-# OPTIONS_GHC -F -pgmF hspec-discover #-}
EOF

# "${LIB_U}"Spec.hs:
cat > test/"${LIB_U}"Spec.hs << EOF
module ${LIB_U}Spec (main, spec) where

import Test.Hspec
import Test.QuickCheck

import ${LIB_U}

main :: IO ()
main = hspec spec

spec :: Spec
spec = do
  describe "Basic tests" $ do
    it "___DUMMY___" $ do
      id 42 \`shouldBe\` 42
EOF

# Lastly we'll add some shell content for the project to compile:
cat > src/"${LIB_U}".hs << EOF
module ${LIB_U} where

${LIB_L} :: undefined
${LIB_L}  = undefined
EOF

# git:
cat > .gitignore << EOF
*~
*#
.#*
*.lock
.cabal-sandbox
cabal.sandbox.config
.stack-work
/**/dist/
/**/TAGS
EOF

##############

stack test && git init -q
git add\
 src/ test/\
 package.yaml\
 CHANGELOG.md LICENSE README.md\
 Setup.hs stack.yaml "${LIB_L}".cabal\
 .gitignore
git status
git commit -am "Create skeleton. Add ${LIB_U}.hs and ${LIB_U}Spec.hs"

echo "
Current git log:"
git log --graph --pretty=format:'%C(red)%h% %C(green) (%cd)%C(reset) %s %C(yellow)%d%C(reset)' --abbrev-commit --date=short

##############

# README.md    (GitLab / GitHub / ...)
# this file is placed into the .stack-work hidden directory.
# It would be helpful when you upload the repository to GitLab/GitHub/ ...

if [[ ${GITLAB_GITHUB^^}  == "GITLAB" ]] ; then
  GITLAB_GITHUB_USER=$(eval "git config --get gitlab.user")
elif [[ ${GITLAB_GITHUB^^}  == "GITHUB" ]] ; then
  GITLAB_GITHUB_USER=$(eval "git config --get github.user")
fi

cat > "${LIBROOT}"/"${LIB_L}${DATA}"/.stack-work/README.md << EOF
# ${LIB_U}
LIB: ${LIB_L} (BDD/TDD Style) - "${LIB_U}"

    git clone https://${GITLAB_GITHUB}.com/${GITLAB_GITHUB_USER}/${LIB_L}
    cd "${LIB_L}" || (echo "** ERROR(3): cd **" ; exit 1)
    stack test
EOF

# cdargs:
touch ~/.cdargs
(echo "${LIB_L} ${LIBROOT}/${LIB_L}${DATA}" && cat ~/.cdargs) > ~/.cdargs_tmp && mv ~/.cdargs_tmp ~/.cdargs

# Some help:
echo -e "
${B}git${B_} is now particulary taking care of:
    ${LIBROOT}/${LIB_L}${DATA}/${B}src/${LIB_U}.hs${B_}
    ${LIBROOT}/${LIB_L}${DATA}/${B}test/${LIB_U}Spec.hs${B_}
    ${LIBROOT}/${LIB_L}${DATA}/${B}package.yaml${B_}
    ${LIBROOT}/${LIB_L}${DATA}/${B}stack.yaml${B_}

${U}Remember${B_}:
${B}cdargs${B_} or ${B}cdb${B_}  # (hit 'Enter' twice)  to visit your kata's directory
  (cd ${LIBROOT}/${LIB_U})
${B}stack test${B_} # Compile, and if success, run tests"

if [[ ${DATA} == ".data" ]]; then
    mv "${LIBROOT}/${LIB_L}" "${LIBROOT}/${LIB_L}${DATA}" || (echo "** ERROR(6): cd **" ; exit 1)
  if [ -d "${LIBROOT}/${LIB_L}_TMP" ]; then
    mv "${LIBROOT}/${LIB_L}_TMP" "${LIBROOT}/${LIB_L}" || (echo "** ERROR(8): cd **" ; exit 1)
  fi
fi
}


function editor_and_terminals()
{
echo "export PS1='\[\e]0;HaskellKatas\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" | xclip -selection primary
xdotool windowactivate --sync "$WINDOWID"
xdotool key Shift+Insert+Return

sleep 0.1

cd "${LIBROOT}/${LIB_L}${DATA}" || (echo "** ERROR(4): cd **" ; exit 1)

if [[ ${DATA} == ".data" ]]; then
  LOG_AND_INSTRUCTIONS="${PROGRAM_NAME} --log4 -i"
else
  LOG_AND_INSTRUCTIONS="${PROGRAM_NAME} --log -i"
fi

# editor
emacs -T "${EDITOR_NAME}${LIB_U}" --no-splash --geometry="${GEOM_EMACS}" \
      "stack.yaml" "package.yaml" "src/${LIB_U}.hs" "test/${LIB_U}Spec.hs" \
      2>&1 &

sleep 1
# term 0 stack ghci (hidden)
xterm -xrm "xterm*allowTitleOps: false" -title "${TERMINAL_NAMES[0]}" -fa 'Monospace' -fs 11 -geometry ${GEOM_TERM0} &
sleep 0.2
# term 1 git diff
xterm -xrm "xterm*allowTitleOps: false" -title "${TERMINAL_NAMES[1]}" -fa 'Monospace' -fs 11 -geometry ${GEOM_TERM1} &
sleep 0.2
# term 2 stack build
xterm -xrm "xterm*allowTitleOps: false" -title "${TERMINAL_NAMES[2]}" -fa 'Monospace' -fs 11 -geometry ${GEOM_TERM2} &
sleep 0.2
# term 3 Command - git
xterm -xrm "xterm*allowTitleOps: false" -title "${TERMINAL_NAMES[3]}" -fa 'Monospace' -fs 11 -geometry ${GEOM_TERM3} -si &
sleep 1
##
# term 0 stack ghci (hidden)
TERMINAL_WINDOWS0=$( { xdotool search --name "${TERMINAL_NAMES[0]}"; } )
xdotool windowactivate --sync "${TERMINAL_WINDOWS0}" 2>/dev/null
sleep 0.2
echo  "stack exec -- ghci src/${LIB_U}.hs test/${LIB_U}Spec.hs" | xclip -selection primary
xdotool key Shift+Insert+Return
sleep 1

# term 1 git diff
TERMINAL_WINDOWS1=$( { xdotool search --name "${TERMINAL_NAMES[1]}"; } )
xdotool windowactivate --sync "${TERMINAL_WINDOWS1}" 2>/dev/null
sleep 0.2

echo "(while inotifywait -e modify package.yaml src/ test/; \
 do pkill pager ; touch .stack-work/tRiGgEr ; sleep 1 ; \
 rm .stack-work/tRiGgEr 2> /dev/null; done ;) & \
 while inotifywait -e delete .stack-work ; \
 do clear ; git diff package.yaml src/ test/ ; \
 done" | xclip -selection primary
xdotool key Shift+Insert+Return
sleep 1

# term 2 stack build
TERMINAL_WINDOWS2=$( { xdotool search --name "${TERMINAL_NAMES[2]}"; } )
xdotool windowactivate --sync "${TERMINAL_WINDOWS2}" 2>/dev/null
sleep 0.2
echo "stack build --test --file-watch --fast" | xclip -selection primary
xdotool key Shift+Insert+Return
sleep 1

# term 3 Command - git
TERMINAL_WINDOWS3=$( { xdotool search --name "${TERMINAL_NAMES[3]}"; } )
xdotool windowactivate --sync "${TERMINAL_WINDOWS3}" 2>/dev/null
sleep 0.2
echo "${README}
${LOG_AND_INSTRUCTIONS}" | xclip -selection primary
xdotool key Shift+Insert+Return
sleep 0.2
}


# Program start

check "$@"

wmctrl -lp | grep "Command - git" >/dev/null 2>&1
if [ "$?" -eq 0 ] ; then
  quit_windows
fi

if [[ ${EDIT_EXISTING_KATA} != "YES" ]]; then
  if   [[ ${LIBROOT} == "${LIBROOT_CW}" ]]; then
    createNewKataCW
  fi
fi

editor_and_terminals "${LIB_L}"
echo "Enjoy!"
